#Data configs

data:
  train_path: "/run/media/francesco/STORAGE/Coll_2V_VBFHbb_preliminary_prove/Train"
  val_path: "/run/media/francesco/STORAGE/Coll_2V_VBFHbb_preliminary_prove/Val"
  test_path: "/run/media/francesco/STORAGE/Coll_2V_VBFHbb_preliminary_prove/Test"
  max_particles: 128
  preprocessing: True
  features: 
    - L1T_PUPPIPart_PT
    - L1T_PUPPIPart_Eta 
    - L1T_PUPPIPart_Phi
    - L1T_PUPPIPart_PuppiW
